<?php
declare(strict_types=1);
namespace MyGame\Infrastructure\Market;
use PDO;
final class BusinessOperationsRepository{
 public function __construct(private PDO $pdo){}
 public function properties(int $companyId):array{$company=$this->one('SELECT city,industry FROM companies WHERE id=?',[$companyId]);if(!$company)return[];$allowed=$this->allowedPropertyTypes((string)$company['industry']);$marks=implode(',',array_fill(0,count($allowed),'?'));$s=$this->pdo->prepare("SELECT * FROM property_market WHERE is_available=1 AND city=? AND property_type IN ($marks) ORDER BY monthly_rent,area_m2");$s->execute([$company['city'],...$allowed]);return$s->fetchAll();}
 public function rentProperty(int $companyId,int $id):void{$company=$this->one('SELECT city,industry FROM companies WHERE id=?',[$companyId]);if(!$company)throw new \RuntimeException('Įmonė nerasta.');$this->pdo->beginTransaction();try{$p=$this->one('SELECT * FROM property_market WHERE id=? AND is_available=1 FOR UPDATE',[$id]);if(!$p)throw new \RuntimeException('Objektas nepasiekiamas.');if((string)$p['city']!==(string)$company['city'])throw new \RuntimeException('Galima nuomotis tik įmonės mieste esančias patalpas.');if(!in_array((string)$p['property_type'],$this->allowedPropertyTypes((string)$company['industry']),true))throw new \RuntimeException('Šio tipo patalpos netinka pasirinktai įmonės veiklai.');$this->pdo->prepare('INSERT INTO company_properties(company_id,market_property_id,property_type,city,area_m2,monthly_rent) VALUES(?,?,?,?,?,?)')->execute([$companyId,$id,$p['property_type'],$p['city'],$p['area_m2'],$p['monthly_rent']]);$this->pdo->prepare('UPDATE property_market SET is_available=0 WHERE id=?')->execute([$id]);$this->pdo->commit();}catch(\Throwable$e){if($this->pdo->inTransaction())$this->pdo->rollBack();throw$e;}}
 public function terminateProperty(int $companyId,int $propertyId):void{$this->pdo->beginTransaction();try{$p=$this->one("SELECT * FROM company_properties WHERE id=? AND company_id=? AND status='active' FOR UPDATE",[$propertyId,$companyId]);if(!$p)throw new \RuntimeException('Aktyvi nuomos sutartis nerasta.');$this->pdo->prepare("UPDATE company_properties SET status='terminated' WHERE id=?")->execute([$propertyId]);if(!empty($p['market_property_id']))$this->pdo->prepare('UPDATE property_market SET is_available=1 WHERE id=?')->execute([$p['market_property_id']]);$this->pdo->commit();}catch(\Throwable$e){if($this->pdo->inTransaction())$this->pdo->rollBack();throw$e;}}
 public function roles(int $companyId=0):array{if($companyId<=0)return$this->pdo->query('SELECT * FROM job_roles ORDER BY base_salary')->fetchAll();$c=$this->one('SELECT industry FROM companies WHERE id=?',[$companyId]);$codes=$this->allowedRoleCodes((string)($c['industry']??'retail'));$marks=implode(',',array_fill(0,count($codes),'?'));$s=$this->pdo->prepare("SELECT * FROM job_roles WHERE code IN ($marks) ORDER BY base_salary");$s->execute($codes);return$s->fetchAll();}
 public function employees(int $id):array{$s=$this->pdo->prepare("SELECT e.*,r.name role_name,r.code role_code FROM company_employees e JOIN job_roles r ON r.id=e.role_id WHERE e.company_id=? AND e.status='active' ORDER BY e.id");$s->execute([$id]);return$s->fetchAll();}
 public function hire(int $companyId,int $roleId,float $salary):void{$r=$this->one('SELECT * FROM job_roles WHERE id=?',[$roleId]);if(!$r)throw new \RuntimeException('Pareigybė nerasta.');$c=$this->one('SELECT industry FROM companies WHERE id=?',[$companyId]);if(!in_array((string)$r['code'],$this->allowedRoleCodes((string)($c['industry']??'retail')),true))throw new \RuntimeException('Ši pareigybė netinka pasirinktai įmonės veiklai.');$min=$this->param('minimum_wage');if($salary<max($min,(float)$r['base_salary']*.75))throw new \RuntimeException('Siūlomas atlyginimas per mažas.');$names=['Tomas Petrauskas','Mantas Kazlauskas','Ieva Jankauskaitė','Greta Stankevičiūtė','Lukas Vaitkus','Aistė Žukaitė','Darius Paulauskas'];$name=$names[random_int(0,count($names)-1)];$skill=random_int(55,95);$date=(string)($this->pdo->query('SELECT game_date FROM game_clock WHERE id=1')->fetchColumn());$this->pdo->prepare('INSERT INTO company_employees(company_id,role_id,full_name,salary,skill,hired_at) VALUES(?,?,?,?,?,?)')->execute([$companyId,$roleId,$name,$salary,$skill,$date]);$this->syncEmployment($companyId);}
 public function dismiss(int $companyId,int $employeeId):void{$this->pdo->prepare("UPDATE company_employees SET status='dismissed' WHERE id=? AND company_id=?")->execute([$employeeId,$companyId]);$this->syncEmployment($companyId);}
 public function products(int $companyId):array{$c=$this->one('SELECT industry FROM companies WHERE id=?',[$companyId]);$s=$this->pdo->prepare('SELECT p.*,COALESCE(i.quantity,0) quantity,COALESCE(NULLIF(i.sale_price,0),p.base_price) sale_price,COALESCE(i.average_cost,0) average_cost FROM products p LEFT JOIN company_inventory i ON i.product_id=p.id AND i.company_id=? WHERE p.industry=? ORDER BY p.category,p.name');$s->execute([$companyId,$c['industry']??'retail']);return$s->fetchAll();}
 public function suppliers(int $companyId):array{$c=$this->one('SELECT industry FROM companies WHERE id=?',[$companyId]);$s=$this->pdo->prepare('SELECT * FROM suppliers WHERE is_active=1 AND industry=? ORDER BY price_factor,delivery_days');$s->execute([$c['industry']??'retail']);return$s->fetchAll();}
 public function order(int $companyId,int $supplierId,int $productId,float $qty):void{if($qty<=0)throw new \RuntimeException('Neteisingas kiekis.');$ready=$this->readiness($companyId);if(!$ready['has_required_property'])throw new \RuntimeException('Pirmiausia išsinuomokite veiklai tinkamas patalpas.');$sup=$this->one('SELECT * FROM suppliers WHERE id=? AND is_active=1',[$supplierId]);$p=$this->one('SELECT * FROM products WHERE id=?',[$productId]);if(!$sup||!$p)throw new \RuntimeException('Tiekėjas arba prekė nerasta.');if((string)$p['industry']!==(string)($this->one('SELECT industry FROM companies WHERE id=?',[$companyId])['industry']??''))throw new \RuntimeException('Prekė netinka įmonės veiklos sričiai.');if((string)$sup['industry']!==(string)$p['industry'])throw new \RuntimeException('Šis tiekėjas šios prekės netiekia.');$unit=round((float)$p['base_cost']*(float)$sup['price_factor'],2);$transport=round($qty*$unit*.03*($this->param('road_cost_index')/100),2);$customs=$sup['country_code']==='LT'?0:round($qty*$unit*$this->param('customs_rate')/100,2);$vatRate=$this->param('vat');$net=round($qty*$unit+$transport+$customs,2);$inputVat=$sup['country_code']==='LT'?round($net*$vatRate/100,2):0;$total=round($net+$inputVat,2);$date=(string)$this->pdo->query('SELECT game_date FROM game_clock WHERE id=1')->fetchColumn();$arr=(new \DateTimeImmutable($date))->modify('+'.(int)$sup['delivery_days'].' days')->format('Y-m-d');$this->pdo->beginTransaction();try{$this->pdo->prepare("INSERT INTO purchase_orders(company_id,supplier_id,product_id,quantity,unit_cost,transport_cost,customs_cost,total_cost,input_vat,ordered_at,arrives_at,status) VALUES(?,?,?,?,?,?,?,?,?,?,?,'ordered')")->execute([$companyId,$supplierId,$productId,$qty,$unit,$transport,$customs,$total,$inputVat,$date,$arr]);if($inputVat>0)$this->pdo->prepare('INSERT INTO company_tax_accounts(company_id,vat_credit) VALUES(?,?) ON DUPLICATE KEY UPDATE vat_credit=vat_credit+VALUES(vat_credit)')->execute([$companyId,$inputVat]);$flow=new \MyGame\Infrastructure\Economy\MoneyFlowService($this->pdo);if(!empty($sup['company_id']))$flow->companyToCompany($companyId,(int)$sup['company_id'],$total,'supplier_payment','Prekių užsakymas · '.$sup['name']);else{$sector=($sup['supplier_type']??($sup['country_code']==='LT'?'domestic':'foreign'))==='domestic'?'DOMESTIC_BUSINESS':'FOREIGN';$flow->companyToSector($companyId,$sector,$total,$sector==='FOREIGN'?'import_payment':'supplier_payment',($sector==='FOREIGN'?'Importas':'Pirkimas Lietuvoje').' · '.$sup['name']);}$this->pdo->commit();}catch(\Throwable$e){if($this->pdo->inTransaction())$this->pdo->rollBack();throw$e;}}
 public function orders(int $companyId):array{$s=$this->pdo->prepare('SELECT o.*,s.name supplier_name,p.name product_name FROM purchase_orders o JOIN suppliers s ON s.id=o.supplier_id JOIN products p ON p.id=o.product_id WHERE o.company_id=? ORDER BY o.id DESC LIMIT 20');$s->execute([$companyId]);return$s->fetchAll();}
 public function setPrice(int $companyId,int $productId,float $price):void{if($price<=0)throw new \RuntimeException('Neteisinga kaina.');$this->pdo->prepare('INSERT INTO company_inventory(company_id,product_id,sale_price) VALUES(?,?,?) ON DUPLICATE KEY UPDATE sale_price=VALUES(sale_price)')->execute([$companyId,$productId,$price]);}
 public function marketing(int $companyId,float $budget):void{if($budget<0)throw new \RuntimeException('Neteisingas biudžetas.');$this->pdo->prepare('INSERT INTO company_marketing(company_id,monthly_budget) VALUES(?,?) ON DUPLICATE KEY UPDATE monthly_budget=VALUES(monthly_budget)')->execute([$companyId,$budget]);}
 public function marketingData(int $id):array{return$this->one('SELECT * FROM company_marketing WHERE company_id=?',[$id])?:['monthly_budget'=>0,'brand_awareness'=>50,'reputation'=>70];}
 public function contracts(int $companyId):array{
  $properties=$this->all("SELECT id,market_property_id,property_type,city,area_m2,monthly_rent,status FROM company_properties WHERE company_id=? AND status='active' ORDER BY id DESC",[$companyId]);
  $utilities=$this->all("SELECT utility_type,monthly_usage,is_active FROM company_utility_contracts WHERE company_id=? AND is_active=1 ORDER BY utility_type",[$companyId]);
  $employees=$this->all("SELECT e.full_name,e.salary,e.skill,r.name role_name,r.code role_code FROM company_employees e JOIN job_roles r ON r.id=e.role_id WHERE e.company_id=? AND e.status='active' ORDER BY e.id",[$companyId]);
  return ['properties'=>$properties,'utilities'=>$utilities,'employees'=>$employees];
 }
 public function readiness(int $companyId):array{$c=$this->one('SELECT city,industry FROM companies WHERE id=?',[$companyId]);$industry=(string)($c['industry']??'retail');$city=(string)($c['city']??'');$types=$this->allowedPropertyTypes($industry);$marks=implode(',',array_fill(0,count($types),'?'));$s=$this->pdo->prepare("SELECT COUNT(*) c FROM company_properties WHERE company_id=? AND status='active' AND city=? AND property_type IN ($marks)");$s->execute([$companyId,$city,...$types]);$property=(int)$s->fetchColumn()>0;$workers=$this->operationalRoleCodes($industry);$marks2=implode(',',array_fill(0,count($workers),'?'));$e=$this->pdo->prepare("SELECT COUNT(*) FROM company_employees e JOIN job_roles r ON r.id=e.role_id WHERE e.company_id=? AND e.status='active' AND r.code IN ($marks2)");$e->execute([$companyId,...$workers]);$employee=(int)$e->fetchColumn()>0;$requiredUtilities=$this->requiredUtilities($industry);$u=$this->pdo->prepare("SELECT utility_type FROM company_utility_contracts WHERE company_id=? AND is_active=1 AND monthly_usage>0");$u->execute([$companyId]);$active=array_column($u->fetchAll(),'utility_type');$missing=array_values(array_diff($requiredUtilities,$active));$stock=(int)($this->one('SELECT COUNT(*) c FROM company_inventory WHERE company_id=? AND quantity>0',[$companyId])['c']??0);return['industry'=>$industry,'has_required_property'=>$property,'has_operational_employee'=>$employee,'required_utilities'=>$requiredUtilities,'missing_utilities'=>$missing,'has_stock'=>$stock>0,'stock_products'=>$stock,'ready'=>$property&&$employee&&!$missing&&$stock>0,'property_types'=>$types,'operational_roles'=>$workers];}
 private function allowedPropertyTypes(string $i):array{return match($i){'retail'=>['shop'],'logistics'=>['warehouse'],'manufacturing'=>['factory'],'services'=>['office'],default=>['office']};}
 private function allowedRoleCodes(string $i):array{return array_values(array_unique(array_merge($this->operationalRoleCodes($i),['accountant','manager','marketing'])));}
 private function operationalRoleCodes(string $i):array{return match($i){'retail'=>['seller'],'logistics'=>['driver','warehouse'],'manufacturing'=>['production','warehouse'],'services'=>['manager'],default=>['manager']};}
 private function requiredUtilities(string $i):array{return match($i){'retail'=>['electricity','water'],'logistics'=>['electricity'],'manufacturing'=>['electricity','water'],'services'=>['electricity'],default=>['electricity']};}
 private function syncEmployment(int $id):void{$x=$this->one("SELECT COUNT(*) c,COALESCE(AVG(salary),0) a FROM company_employees WHERE company_id=? AND status='active'",[$id]);$this->pdo->prepare('INSERT INTO company_employment(company_id,employees,average_salary) VALUES(?,?,?) ON DUPLICATE KEY UPDATE employees=VALUES(employees),average_salary=VALUES(average_salary)')->execute([$id,$x['c'],$x['a']]);}
 private function all(string $sql,array $p=[]):array{$s=$this->pdo->prepare($sql);$s->execute($p);return$s->fetchAll();}
 private function param(string $k):float{$r=$this->one('SELECT value FROM economic_parameters WHERE parameter_key=?',[$k]);return(float)($r['value']??0);}
 private function one(string $sql,array $p=[]):array|false{$s=$this->pdo->prepare($sql);$s->execute($p);return$s->fetch();}
}
