<?php
declare(strict_types=1);
namespace MyGame\Infrastructure\Economy;
use PDO;
final class GameEconomyEngine{
 public function __construct(private PDO $pdo){}
 public function clock():array{$row=$this->pdo->query('SELECT * FROM game_clock WHERE id=1')->fetch()?:[];$offset=(int)($row['test_offset_days']??0);$row['game_date']=(new \DateTimeImmutable('today'))->modify(($offset>=0?'+':'').$offset.' day')->format('Y-m-d');return$row;}
 public function sync():string{$clock=$this->clock();$target=(string)$clock['game_date'];$last=(string)($clock['last_processed_date']??'');$ai=new AiCompanyEngine($this->pdo);$ai->seed();if($last===''||$last>$target){$this->pdo->prepare('UPDATE game_clock SET game_date=?,last_processed_date=? WHERE id=1')->execute([$target,$target]);$this->backfillAiCycles($target);$this->refreshAllObligations();$this->runAutoAccountingForAll();return$target;}$from=new \DateTimeImmutable($last);$to=new \DateTimeImmutable($target);$this->pdo->prepare('UPDATE game_clock SET game_date=? WHERE id=1')->execute([$target]);$this->deliverOrders($target);$this->refreshLoanPayments();$cursor=$from->modify('first day of next month');while($cursor<=$to){$period=$cursor->modify('-1 month')->format('Y-m');$this->processMonth($period);$cursor=$cursor->modify('+1 month');}$this->ensureAiMonthlyCycles($target);$this->backfillAiCycles($target);$this->refreshAllObligations();$this->runAutoAccountingForAll();$this->pdo->prepare('UPDATE game_clock SET last_processed_date=? WHERE id=1')->execute([$target]);return$target;}
 public function auditAndRepairAiCycles(?string $target=null):array{
  $target=$target?:((string)$this->clock()['game_date']);
  $period=(new \DateTimeImmutable($target))->modify('first day of this month')->modify('-1 month')->format('Y-m');
  $out=[];
  foreach($this->pdo->query("SELECT id,name,status FROM companies WHERE company_type='ai' ORDER BY id") as $row){
   $id=(int)$row['id'];
   $before=$this->one('SELECT id FROM company_monthly_cycles WHERE company_id=? AND period=?',[$id,$period]);
   $employees=(int)($this->one("SELECT COUNT(*) c FROM company_employees WHERE company_id=? AND status='active'",[$id])['c']??0);
   $inventory=(int)($this->one('SELECT COUNT(*) c FROM company_inventory WHERE company_id=? AND quantity>0',[$id])['c']??0);
   $accountRow=$this->one('SELECT COUNT(*) c,COALESCE(SUM(balance),0) balance FROM company_bank_accounts WHERE company_id=? AND is_primary=1 AND is_active=1',[$id]);
   $account=(int)($accountRow['c']??0);$balance=(float)($accountRow['balance']??0);
   $statusBefore=(string)$row['status'];$status=$statusBefore;$repairedStatus=false;$error=null;
   if($status!=='active'&&$balance>0&&$employees>0){$this->pdo->prepare("UPDATE companies SET status='active' WHERE id=? AND company_type='ai'")->execute([$id]);$status='active';$repairedStatus=true;}
   if(!$before&&$status==='active'){try{$this->processCompanyMonth($id,$period);}catch(\Throwable $e){$error=get_class($e).': '.$e->getMessage();}}
   $after=$this->one('SELECT id,revenue,payroll_cost,payroll_tax,vat_due,profit_tax_due FROM company_monthly_cycles WHERE company_id=? AND period=?',[$id,$period]);
   $out[]=['id'=>$id,'name'=>$row['name'],'period'=>$period,'status_before'=>$statusBefore,'status'=>$status,'status_repaired'=>$repairedStatus,'balance'=>$balance,'employees'=>$employees,'inventory'=>$inventory,'account'=>$account,'cycle_before'=>(bool)$before,'cycle_after'=>(bool)$after,'cycle'=>$after?:null,'error'=>$error];
  }
  return$out;
 }
 public function advance(int $days=1):string{$days=max(1,min(31,$days));$this->pdo->prepare('UPDATE game_clock SET test_offset_days=test_offset_days+? WHERE id=1')->execute([$days]);return$this->sync();}
 public function resetTestOffset():string{$this->pdo->exec('UPDATE game_clock SET test_offset_days=0,last_processed_date=CURRENT_DATE,game_date=CURRENT_DATE WHERE id=1');return date('Y-m-d');}
 public function clearTestHistory():void{$this->pdo->beginTransaction();try{$this->pdo->exec("DELETE FROM company_payment_arrears");$this->pdo->exec("DELETE FROM payroll_ledger");$this->pdo->exec("DELETE FROM company_obligations");$this->pdo->exec("DELETE FROM sales_ledger");$this->pdo->exec("DELETE FROM company_monthly_cycles");$this->pdo->exec("DELETE FROM economy_snapshots");$this->pdo->exec("DELETE FROM economy_sector_transactions");$this->pdo->exec("DELETE FROM state_bank_transactions");$this->pdo->exec("DELETE FROM state_expenses");$this->pdo->exec("UPDATE state_bank_accounts SET balance=0");$this->pdo->exec("DELETE FROM bank_account_transactions WHERE reference_type IN ('obligation','operating_cost') OR transaction_type IN ('salary_payment','sales_revenue','rent','utilities','marketing_expense','state_payment')");$this->pdo->exec("UPDATE companies SET monthly_revenue=0,monthly_profit=0");$this->pdo->exec("UPDATE company_tax_accounts SET vat_credit=0,tax_loss_carryforward=0");$this->pdo->exec("UPDATE game_clock SET test_offset_days=0,game_date=CURRENT_DATE,last_processed_date=CURRENT_DATE WHERE id=1");$this->pdo->commit();}catch(\Throwable $e){if($this->pdo->inTransaction())$this->pdo->rollBack();throw $e;}}
 private function deliverOrders(string $date):void{$s=$this->pdo->prepare("SELECT * FROM purchase_orders WHERE status='ordered' AND arrives_at<=?");$s->execute([$date]);foreach($s as $o){$inv=$this->one('SELECT * FROM company_inventory WHERE company_id=? AND product_id=?',[$o['company_id'],$o['product_id']]);$oldQty=(float)($inv['quantity']??0);$oldCost=(float)($inv['average_cost']??0);$qty=(float)$o['quantity'];$landed=((float)$o['total_cost']-(float)($o['input_vat']??0))/$qty;$newQty=$oldQty+$qty;$avg=$newQty>0?(($oldQty*$oldCost)+($qty*$landed))/$newQty:$landed;$this->pdo->prepare('INSERT INTO company_inventory(company_id,product_id,quantity,average_cost,sale_price) VALUES(?,?,?,?,0) ON DUPLICATE KEY UPDATE quantity=VALUES(quantity),average_cost=VALUES(average_cost)')->execute([$o['company_id'],$o['product_id'],$newQty,round($avg,4)]);$this->pdo->prepare("UPDATE purchase_orders SET status='delivered' WHERE id=?")->execute([$o['id']]);}}
 private function ensureAiMonthlyCycles(string $target):void{$period=(new \DateTimeImmutable($target))->modify('first day of this month')->modify('-1 month')->format('Y-m');foreach($this->pdo->query("SELECT id FROM companies WHERE company_type='ai' AND status='active'") as $row){$id=(int)$row['id'];if(!$this->one('SELECT id FROM company_monthly_cycles WHERE company_id=? AND period=?',[$id,$period]))$this->processCompanyMonth($id,$period);}}
 private function backfillAiCycles(string $target):void{$period=(new \DateTimeImmutable($target))->modify('first day of this month')->modify('-1 month')->format('Y-m');foreach($this->pdo->query("SELECT id FROM companies WHERE company_type='ai' AND status='active'") as $c){$id=(int)$c['id'];$cycle=$this->one('SELECT * FROM company_monthly_cycles WHERE company_id=? AND period=?',[$id,$period]);if(!$cycle){$this->processCompanyMonth($id,$period);continue;}$due=(new \DateTimeImmutable($period.'-01'))->modify('+1 month +14 days')->format('Y-m-d');$defs=[['VMI','vat','PVM',(float)$cycle['vat_due']],['VMI','profit_tax','Pelno mokestis',(float)$cycle['profit_tax_due']],['SODRA','payroll_tax','Darbo mokesčiai',(float)$cycle['payroll_tax']]];foreach($defs as $o){if($o[3]<=0)continue;if($this->one('SELECT id FROM company_obligations WHERE company_id=? AND obligation_type=? AND description=?',[$id,$o[1],$o[2].' · '.$period]))continue;$this->pdo->prepare("INSERT INTO company_obligations(company_id,institution,obligation_type,description,amount,due_at,status) VALUES(?,?,?,?,?,?,'pending')")->execute([$id,$o[0],$o[1],$o[2].' · '.$period,$o[3],$due]);}}}
 private function processMonth(string $period):void{$ai=new AiCompanyEngine($this->pdo);$ai->seed();foreach($this->pdo->query("SELECT id FROM companies WHERE status='active'") as $c)$this->processCompanyMonth((int)$c['id'],$period);$ai->runMonth();$this->updateEconomy($period);}
 private function processCompanyMonth(int $id,string $period):void{
  if($this->one('SELECT id FROM company_monthly_cycles WHERE company_id=? AND period=?',[$id,$period]))return;$c=$this->one('SELECT * FROM companies WHERE id=?',[$id]);if(!$c)return;
  $emp=false;$rent=(float)($this->one("SELECT COALESCE(SUM(monthly_rent),0) v FROM company_properties WHERE company_id=? AND status='active'",[$id])['v']??0);$utilities=$this->utilityCost($id);$payroll=$this->payroll($id,$emp);$payrollTax=round($payroll*$this->param('payroll_burden')/100,2);[$revenue,$stockCost]=$this->salesRevenue($c,$period);$vatRate=$this->param('vat');$outputVat=round(max(0,$revenue)*$vatRate/(100+$vatRate),2);$tax=$this->one('SELECT * FROM company_tax_accounts WHERE company_id=?',[$id]);$inputVat=(float)($tax['vat_credit']??0);$vat=max(0,round($outputVat-$inputVat,2));$vatCredit=max(0,round($inputVat-$outputVat,2));$this->pdo->prepare('INSERT INTO company_tax_accounts(company_id,vat_credit) VALUES(?,?) ON DUPLICATE KEY UPDATE vat_credit=VALUES(vat_credit)')->execute([$id,$vatCredit]);$marketing=(float)($this->one('SELECT monthly_budget v FROM company_marketing WHERE company_id=?',[$id])['v']??0);$operating=$revenue-$stockCost-$rent-$utilities-$payroll-$payrollTax-$marketing;$loss=(float)($tax['tax_loss_carryforward']??0);$taxable=max(0,$operating-$loss);$newLoss=$operating<0?$loss+abs($operating):max(0,$loss-max(0,$operating));$profitTax=round($taxable*$this->param('profit_tax')/100,2);$this->pdo->prepare('INSERT INTO company_tax_accounts(company_id,tax_loss_carryforward) VALUES(?,?) ON DUPLICATE KEY UPDATE tax_loss_carryforward=VALUES(tax_loss_carryforward)')->execute([$id,$newLoss]);$net=$operating-$profitTax;$this->settleOperatingCosts($id,$period,$rent,$utilities,$marketing);$this->settlePayroll($id,$period);
  $this->pdo->prepare('INSERT INTO company_monthly_cycles(company_id,period,revenue,stock_cost,rent_cost,utility_cost,marketing_cost,payroll_cost,payroll_tax,vat_due,input_vat,taxable_result,profit_tax_due) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)')->execute([$id,$period,$revenue,$stockCost,$rent,$utilities,$marketing,$payroll,$payrollTax,$vat,$inputVat,$taxable,$profitTax]);
  $due=(new \DateTimeImmutable($period.'-01'))->modify('+1 month +14 days')->format('Y-m-d');foreach([['VMI','vat','PVM',$vat],['VMI','profit_tax','Pelno mokestis',$profitTax],['SODRA','payroll_tax','Darbo mokesčiai',$payrollTax]] as $o){if($o[3]<=0)continue;$this->pdo->prepare("INSERT INTO company_obligations(company_id,institution,obligation_type,description,amount,due_at,status) VALUES(?,?,?,?,?,?,'pending')")->execute([$id,$o[0],$o[1],$o[2].' · '.$period,$o[3],$due]);}
  $this->pdo->prepare('UPDATE companies SET monthly_revenue=?,monthly_profit=?,age_months=age_months+1 WHERE id=?')->execute([$revenue,$net,$id]);
  $this->autoAccounting($id);
 }
 private function updateEconomy(string $period):void{
  $infl=$this->param('inflation');$gdp=$this->param('gdp_growth');$unemp=$this->param('unemployment');$cc=$this->param('consumer_confidence');$bc=$this->param('business_confidence');$pp=$this->param('purchasing_power');$pi=$this->param('property_price_index');
  $active=(int)$this->pdo->query("SELECT COUNT(*) FROM companies WHERE status='active'")->fetchColumn();$bankrupt=(int)$this->pdo->query("SELECT COUNT(*) FROM companies WHERE status='bankrupt'")->fetchColumn();
  $avg=(float)($this->pdo->query('SELECT COALESCE(AVG(monthly_profit),0) FROM companies')->fetchColumn());$gdp=max(-8,min(10,$gdp+($avg>0?.08:-.12)));$unemp=max(2,min(25,$unemp+($avg>0?-.04:.08)));$cc=max(40,min(160,$cc+($gdp>=0?.15:-.2)-$infl*.01));$bc=max(40,min(160,$bc+($avg>0?.2:-.3)));$pp=max(50,min(160,$pp+(($gdp-$infl)*.03)));$pi=max(50,min(200,$pi+($gdp*.04-$unemp*.01)));
  foreach(['gdp_growth'=>$gdp,'unemployment'=>$unemp,'consumer_confidence'=>$cc,'business_confidence'=>$bc,'purchasing_power'=>$pp,'property_price_index'=>$pi] as $k=>$v)$this->pdo->prepare('UPDATE economic_parameters SET value=? WHERE parameter_key=?')->execute([round($v,4),$k]);
  $this->pdo->prepare('INSERT INTO economy_snapshots(period,inflation,gdp_growth,unemployment,consumer_confidence,business_confidence,purchasing_power,property_index,active_companies,bankruptcies) VALUES(?,?,?,?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE gdp_growth=VALUES(gdp_growth),unemployment=VALUES(unemployment),consumer_confidence=VALUES(consumer_confidence),business_confidence=VALUES(business_confidence),purchasing_power=VALUES(purchasing_power),property_index=VALUES(property_index),active_companies=VALUES(active_companies),bankruptcies=VALUES(bankruptcies)')->execute([$period,$infl,$gdp,$unemp,$cc,$bc,$pp,$pi,$active,$bankrupt]);
  $this->pdo->prepare('UPDATE market_demand SET purchasing_power=?,demand_index=GREATEST(50,LEAST(160,demand_index+(?-100)*0.02+(?-100)*0.03))')->execute([$pp,$cc,$pp]);
 }
 public function refreshObligations(int $id):void{$date=(string)($this->clock()['game_date']??date('Y-m-d'));$s=$this->pdo->prepare('SELECT * FROM company_obligations WHERE company_id=? AND paid_at IS NULL');$s->execute([$id]);foreach($s as $o){$days=(int)floor((strtotime($date)-strtotime(substr((string)$o['due_at'],0,10)))/86400);$days=max(0,$days);$pen=$days>=2?round((float)$o['amount']*.0005*($days-1),2):0;$this->pdo->prepare('UPDATE company_obligations SET penalty_amount=?,status=? WHERE id=?')->execute([$pen,$days>0?'late':'pending',$o['id']]);}}
 private function refreshLoanPayments():void{$gameDate=(string)($this->clock()['game_date']??date('Y-m-d'));$s=$this->pdo->query("SELECT lp.* FROM loan_payments lp JOIN company_loans l ON l.id=lp.loan_id WHERE l.status='active' AND lp.paid_at IS NULL");foreach($s as $p){$due=substr((string)$p['due_at'],0,10);$days=max(0,(int)floor((strtotime($gameDate)-strtotime($due))/86400));$penalty=$days>=2?round((float)$p['scheduled_amount']*.0005*($days-1),2):0;$status=$gameDate<$due?'waiting':($days<=1?'due':'late');$this->pdo->prepare('UPDATE loan_payments SET penalty_amount=?,status=? WHERE id=?')->execute([$penalty,$status,$p['id']]);}}
 private function refreshAllObligations():void{foreach($this->pdo->query('SELECT id FROM companies') as $c)$this->refreshObligations((int)$c['id']);}
 public function payObligation(int $companyId,int $id):void{$this->pdo->beginTransaction();try{$o=$this->one('SELECT * FROM company_obligations WHERE id=? AND company_id=? AND paid_at IS NULL FOR UPDATE',[$id,$companyId]);if(!$o)throw new \RuntimeException('Mokėjimas nerastas.');$a=$this->one('SELECT * FROM company_bank_accounts WHERE company_id=? AND is_primary=1 AND is_active=1 LIMIT 1',[$companyId]);if(!$a)throw new \RuntimeException('Nėra pagrindinės banko sąskaitos.');$sum=(float)$o['amount']+(float)$o['penalty_amount'];if((float)$a['balance']<$sum)throw new \RuntimeException('Nepakanka lėšų pagrindinėje sąskaitoje.');$bal=(float)$a['balance']-$sum;$this->pdo->prepare('UPDATE company_bank_accounts SET balance=? WHERE id=?')->execute([$bal,$a['id']]);$treasury=new \MyGame\Infrastructure\State\StateTreasuryRepository($this->pdo);$recipient=$treasury->credit($companyId,(string)$o['institution'],$sum,(string)$o['obligation_type'],$id,(string)$o['description']);$this->pdo->prepare("UPDATE company_obligations SET institution_id=?,recipient_account_id=?,paid_at=(SELECT game_date FROM game_clock WHERE id=1),status='paid' WHERE id=?")->execute([$recipient['institution_id'],$recipient['account_id'],$id]);$this->pdo->prepare('INSERT INTO bank_account_transactions(account_id,transaction_type,amount,balance_after,reference_type,reference_id,description,game_date) VALUES(?,?,?,?,?,?,?,(SELECT game_date FROM game_clock WHERE id=1))')->execute([$a['id'],'state_payment',-$sum,$bal,'obligation',$id,'Mokėjimas → '.$recipient['name'].' · '.$o['description']]);$this->pdo->commit();}catch(\Throwable$e){if($this->pdo->inTransaction())$this->pdo->rollBack();throw$e;}}
 private function settlePayroll(int $id,string $period):void{$s=$this->pdo->prepare("SELECT e.* FROM company_employees e WHERE e.company_id=? AND e.status='active'");$s->execute([$id]);$flow=new MoneyFlowService($this->pdo);foreach($s as $e){if($this->one('SELECT id FROM payroll_ledger WHERE company_id=? AND employee_id=? AND period=?',[$id,$e['id'],$period]))continue;$gross=(float)$e['salary'];$tax=round($gross*$this->param('payroll_burden')/100,2);$net=$gross;try{$this->pdo->beginTransaction();$flow->companyToSector($id,'HOUSEHOLDS',$net,'salary_payment','Atlyginimas · '.$e['full_name'].' · '.$period);$this->pdo->prepare("INSERT INTO payroll_ledger(company_id,employee_id,period,gross_amount,tax_amount,net_amount,status,paid_at) VALUES(?,?,?,?,?,?,'paid',(SELECT game_date FROM game_clock WHERE id=1))")->execute([$id,$e['id'],$period,$gross,$tax,$net]);$this->pdo->commit();}catch(\Throwable$x){if($this->pdo->inTransaction())$this->pdo->rollBack();$this->pdo->prepare("INSERT INTO payroll_ledger(company_id,employee_id,period,gross_amount,tax_amount,net_amount,status) VALUES(?,?,?,?,?,?,'due')")->execute([$id,$e['id'],$period,$gross,$tax,$net]);$this->pdo->prepare("INSERT INTO company_payment_arrears(company_id,arrears_type,reference_id,period,amount) VALUES(?,'payroll',?,?,?)")->execute([$id,$e['id'],$period,$net]);}}}
 private function settleOperatingCosts(int $id,string $period,float $rent,float $utilities,float $marketing):void{$flow=new MoneyFlowService($this->pdo);$props=$this->pdo->prepare("SELECT cp.monthly_rent,pm.owner_type,pm.owner_company_id FROM company_properties cp LEFT JOIN property_market pm ON pm.id=cp.market_property_id WHERE cp.company_id=? AND cp.status='active'");$props->execute([$id]);foreach($props as $p){$sum=(float)$p['monthly_rent'];try{if(($p['owner_type']??'state')==='company'&&!empty($p['owner_company_id']))$flow->companyToCompany($id,(int)$p['owner_company_id'],$sum,'rent_payment','Patalpų nuoma · '.$period);else$this->payDirectState($id,'NT',$sum,'rent','Patalpų nuoma · '.$period);}catch(\Throwable$e){$this->arrear($id,'rent',$period,$sum);}}$u=$this->pdo->prepare('SELECT * FROM company_utility_contracts WHERE company_id=? AND is_active=1');$u->execute([$id]);foreach($u as $x){$sum=round((float)$x['monthly_usage']*$this->param((string)$x['utility_type']),2);try{if(($x['provider_type']??'state')==='company'&&!empty($x['provider_company_id']))$flow->companyToCompany($id,(int)$x['provider_company_id'],$sum,'utility_payment','Komunalinės paslaugos · '.$period);else$this->payDirectState($id,'UTILITIES',$sum,'utilities','Komunalinės paslaugos · '.$period);}catch(\Throwable$e){$this->arrear($id,'utilities',$period,$sum);}}if($marketing>0){try{$flow->companyToSector($id,'HOUSEHOLDS',$marketing,'marketing_expense','Marketingo paslaugos · '.$period);}catch(\Throwable$e){$this->arrear($id,'marketing',$period,$marketing);}}}
 private function payDirectState(int $companyId,string $code,float $amount,string $type,string $description):void{if($amount<=0)return;$ownTx=!$this->pdo->inTransaction();if($ownTx)$this->pdo->beginTransaction();try{$a=$this->one('SELECT * FROM company_bank_accounts WHERE company_id=? AND is_primary=1 AND is_active=1 FOR UPDATE',[$companyId]);if(!$a||(float)$a['balance']<$amount)throw new \RuntimeException('Nepakanka lėšų.');$bal=(float)$a['balance']-$amount;$this->pdo->prepare('UPDATE company_bank_accounts SET balance=? WHERE id=?')->execute([$bal,$a['id']]);$treasury=new \MyGame\Infrastructure\State\StateTreasuryRepository($this->pdo);$recipient=$treasury->credit($companyId,$code,$amount,$type,null,$description);$this->pdo->prepare('INSERT INTO bank_account_transactions(account_id,transaction_type,amount,balance_after,reference_type,description,game_date) VALUES(?,?,?,?,?,?,(SELECT game_date FROM game_clock WHERE id=1))')->execute([$a['id'],$type,-$amount,$bal,'operating_cost','Mokėjimas → '.$recipient['name'].' · '.$description]);if($ownTx)$this->pdo->commit();}catch(\Throwable$e){if($ownTx&&$this->pdo->inTransaction())$this->pdo->rollBack();throw$e;}}
 private function arrear(int $id,string $type,string $period,float $amount):void{$this->pdo->prepare("INSERT INTO company_payment_arrears(company_id,arrears_type,period,amount,status) VALUES(?,?,?,?,'due')")->execute([$id,$type,$period,$amount]);}
 private function payroll(int $id,array|false $fallback=false):float{$x=$this->one("SELECT COALESCE(SUM(salary),0) v FROM company_employees WHERE company_id=? AND status='active'",[$id]);return(float)($x['v']??0);}
 private function salesRevenue(array $c,string $period):array{$s=$this->pdo->prepare('SELECT i.*,p.base_price FROM company_inventory i JOIN products p ON p.id=i.product_id WHERE i.company_id=? AND i.quantity>0');$s->execute([$c['id']]);$rows=$s->fetchAll();if(!$rows)return[0,0];$m=$this->one('SELECT * FROM market_demand WHERE city=? AND industry=?',[$c['city'],$c['industry']]);$d=(float)($m['demand_index']??100);$power=(float)($m['purchasing_power']??100);$mk=$this->one('SELECT * FROM company_marketing WHERE company_id=?',[$c['id']]);$brand=(float)($mk['brand_awareness']??50);$budget=(float)($mk['monthly_budget']??0);$revenue=0;$cost=0;foreach($rows as $x){$price=(float)($x['sale_price']?:$x['base_price']);$priceEffect=max(.35,min(1.5,(float)$x['base_price']/$price));$demandUnits=max(1,round((20+$brand*.4+sqrt(max(0,$budget)))*($d/100)*($power/100)*$priceEffect));$qty=min((float)$x['quantity'],$demandUnits);if($qty<=0)continue;$rev=round($qty*$price,2);$cst=round($qty*(float)$x['average_cost'],2);$revenue+=$rev;$cost+=$cst;$this->pdo->prepare('UPDATE company_inventory SET quantity=quantity-? WHERE company_id=? AND product_id=?')->execute([$qty,$c['id'],$x['product_id']]);$this->pdo->prepare('INSERT INTO sales_ledger(company_id,product_id,period,quantity,revenue,cost) VALUES(?,?,?,?,?,?)')->execute([$c['id'],$x['product_id'],$period,$qty,$rev,$cst]);}$flow=new MoneyFlowService($this->pdo);$revenue=$flow->sectorToCompany('HOUSEHOLDS',(int)$c['id'],$revenue,'sales_revenue','Gyventojų pirkimai · '.$period);if($mk){$new=min(100,(float)$mk['brand_awareness']+sqrt(max(0,$budget))*.05);$this->pdo->prepare('UPDATE company_marketing SET brand_awareness=? WHERE company_id=?')->execute([$new,$c['id']]);}return[round($revenue,2),round($cost,2)];}
 private function autoAccounting(int $id):void{$a=$this->one("SELECT e.skill FROM company_employees e JOIN job_roles r ON r.id=e.role_id WHERE e.company_id=? AND e.status='active' AND r.automation_type='accounting' ORDER BY e.skill DESC LIMIT 1",[$id]);if(!$a)return;$this->refreshObligations($id);$s=$this->pdo->prepare("SELECT id FROM company_obligations WHERE company_id=? AND paid_at IS NULL AND due_at<=DATE_ADD((SELECT game_date FROM game_clock WHERE id=1),INTERVAL 3 DAY) ORDER BY due_at");$s->execute([$id]);foreach($s as $o){try{$this->payObligation($id,(int)$o['id']);}catch(\Throwable$e){break;}}}
 public function runAutoAccountingForAll():void{$this->refreshAllObligations();foreach($this->pdo->query("SELECT id FROM companies WHERE status='active'") as $c)$this->autoAccounting((int)$c['id']);}
 private function marketRevenue(array $c):float{$m=$this->one('SELECT * FROM market_demand WHERE city=? AND industry=?',[(string)($c['city']?:'Vilnius'),(string)($c['industry']?:'retail')]);$d=(float)($m['demand_index']??100);$p=(float)($m['purchasing_power']??$this->param('purchasing_power'));$employees=(int)($this->one("SELECT COUNT(*) employees FROM company_employees WHERE company_id=? AND status='active'",[$c['id']])['employees']??0);$competition=(int)($this->one("SELECT COUNT(*) v FROM companies WHERE city=? AND industry=? AND status='active' AND id<>?",[$c['city'],$c['industry'],$c['id']])['v']??0);$capacity=max(1000,$employees*2200);$share=1/(1+$competition*.12);return round($capacity*($d/100)*($p/100)*$share,2);}
 private function utilityCost(int $id):float{$sum=0;$s=$this->pdo->prepare('SELECT * FROM company_utility_contracts WHERE company_id=? AND is_active=1');$s->execute([$id]);foreach($s as $x)$sum+=(float)$x['monthly_usage']*$this->param((string)$x['utility_type']);return round($sum,2);}
 private function param(string $k):float{$r=$this->one('SELECT value FROM economic_parameters WHERE parameter_key=? LIMIT 1',[$k]);return(float)($r['value']??0);}
 private function one(string $sql,array $p=[]):array|false{$s=$this->pdo->prepare($sql);$s->execute($p);return$s->fetch();}
}
