<?php
declare(strict_types=1);
namespace MyGame\Infrastructure\Economy;
use PDO;
final class GameEconomyEngine{
 public function __construct(private PDO $pdo){}
 public function clock():array{return $this->pdo->query('SELECT * FROM game_clock WHERE id=1')->fetch()?:[];}
 public function advance(int $days=1):string{$days=max(1,min(31,$days));$old=$this->clock();$from=new \DateTimeImmutable((string)$old['game_date']);$to=$from->modify('+'.$days.' day');$this->pdo->prepare('UPDATE game_clock SET game_date=? WHERE id=1')->execute([$to->format('Y-m-d')]);$cursor=$from;while($cursor->format('Y-m')!==$to->format('Y-m')){$period=$cursor->format('Y-m');$this->processMonth($period);$cursor=$cursor->modify('first day of next month');}$this->refreshAllObligations();return$to->format('Y-m-d');}
 private function processMonth(string $period):void{$ai=new AiCompanyEngine($this->pdo);$ai->seed();foreach($this->pdo->query("SELECT id FROM companies WHERE status='active'") as $c)$this->processCompanyMonth((int)$c['id'],$period);$ai->runMonth();$this->updateEconomy($period);}
 private function processCompanyMonth(int $id,string $period):void{
  if($this->one('SELECT id FROM company_monthly_cycles WHERE company_id=? AND period=?',[$id,$period]))return;$c=$this->one('SELECT * FROM companies WHERE id=?',[$id]);if(!$c)return;
  $emp=$this->one('SELECT * FROM company_employment WHERE company_id=?',[$id]);$rent=(float)($this->one("SELECT COALESCE(SUM(monthly_rent),0) v FROM company_properties WHERE company_id=? AND status='active'",[$id])['v']??0);$utilities=$this->utilityCost($id);$payroll=$emp?(int)$emp['employees']*(float)$emp['average_salary']:0;$payrollTax=round($payroll*$this->param('payroll_burden')/100,2);$revenue=$this->marketRevenue($c);$vatRate=$this->param('vat');$vat=round(max(0,$revenue)*$vatRate/(100+$vatRate),2);$operating=$revenue-$rent-$utilities-$payroll-$payrollTax;$profitTax=round(max(0,$operating)*$this->param('profit_tax')/100,2);$net=$operating-$profitTax;
  $this->pdo->prepare('INSERT INTO company_monthly_cycles(company_id,period,revenue,rent_cost,utility_cost,payroll_cost,payroll_tax,vat_due,profit_tax_due) VALUES(?,?,?,?,?,?,?,?,?)')->execute([$id,$period,$revenue,$rent,$utilities,$payroll,$payrollTax,$vat,$profitTax]);
  $due=(new \DateTimeImmutable($period.'-01'))->modify('+1 month +14 days')->format('Y-m-d');foreach([['VMI','vat','PVM',$vat],['VMI','profit_tax','Pelno mokestis',$profitTax],['SODRA','payroll_tax','Darbo mokesčiai',$payrollTax],['NT','rent','Patalpų nuoma',$rent],['UTILITIES','utilities','Komunalinės paslaugos',$utilities]] as $o){if($o[3]<=0)continue;$this->pdo->prepare("INSERT INTO company_obligations(company_id,institution,obligation_type,description,amount,due_at,status) VALUES(?,?,?,?,?,?,'pending')")->execute([$id,$o[0],$o[1],$o[2].' · '.$period,$o[3],$due]);}
  $this->pdo->prepare('UPDATE companies SET monthly_revenue=?,monthly_profit=?,cash=cash+?,age_months=age_months+1 WHERE id=?')->execute([$revenue,$net,$revenue,$id]);$a=$this->one('SELECT * FROM company_bank_accounts WHERE company_id=? AND is_primary=1 AND is_active=1',[$id]);if($a){$bal=(float)$a['balance']+$revenue;$this->pdo->prepare('UPDATE company_bank_accounts SET balance=? WHERE id=?')->execute([$bal,$a['id']]);$this->pdo->prepare("INSERT INTO bank_account_transactions(account_id,transaction_type,amount,balance_after,reference_type,description) VALUES(?,'sales_revenue',?,?,'monthly_cycle',?)")->execute([$a['id'],$revenue,$bal,'Pardavimų pajamos · '.$period]);}
 }
 private function updateEconomy(string $period):void{
  $infl=$this->param('inflation');$gdp=$this->param('gdp_growth');$unemp=$this->param('unemployment');$cc=$this->param('consumer_confidence');$bc=$this->param('business_confidence');$pp=$this->param('purchasing_power');$pi=$this->param('property_price_index');
  $active=(int)$this->pdo->query("SELECT COUNT(*) FROM companies WHERE status='active'")->fetchColumn();$bankrupt=(int)$this->pdo->query("SELECT COUNT(*) FROM companies WHERE status='bankrupt'")->fetchColumn();
  $avg=(float)($this->pdo->query('SELECT COALESCE(AVG(monthly_profit),0) FROM companies')->fetchColumn());$gdp=max(-8,min(10,$gdp+($avg>0?.08:-.12)));$unemp=max(2,min(25,$unemp+($avg>0?-.04:.08)));$cc=max(40,min(160,$cc+($gdp>=0?.15:-.2)-$infl*.01));$bc=max(40,min(160,$bc+($avg>0?.2:-.3)));$pp=max(50,min(160,$pp+(($gdp-$infl)*.03)));$pi=max(50,min(200,$pi+($gdp*.04-$unemp*.01)));
  foreach(['gdp_growth'=>$gdp,'unemployment'=>$unemp,'consumer_confidence'=>$cc,'business_confidence'=>$bc,'purchasing_power'=>$pp,'property_price_index'=>$pi] as $k=>$v)$this->pdo->prepare('UPDATE economic_parameters SET value=? WHERE parameter_key=?')->execute([round($v,4),$k]);
  $this->pdo->prepare('INSERT INTO economy_snapshots(period,inflation,gdp_growth,unemployment,consumer_confidence,business_confidence,purchasing_power,property_index,active_companies,bankruptcies) VALUES(?,?,?,?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE gdp_growth=VALUES(gdp_growth),unemployment=VALUES(unemployment),consumer_confidence=VALUES(consumer_confidence),business_confidence=VALUES(business_confidence),purchasing_power=VALUES(purchasing_power),property_index=VALUES(property_index),active_companies=VALUES(active_companies),bankruptcies=VALUES(bankruptcies)')->execute([$period,$infl,$gdp,$unemp,$cc,$bc,$pp,$pi,$active,$bankrupt]);
  $this->pdo->prepare('UPDATE market_demand SET purchasing_power=?,demand_index=GREATEST(50,LEAST(160,demand_index+(?-100)*0.02+(?-100)*0.03))')->execute([$pp,$cc,$pp]);
 }
 public function refreshObligations(int $id):void{$date=(string)($this->clock()['game_date']??date('Y-m-d'));$s=$this->pdo->prepare('SELECT * FROM company_obligations WHERE company_id=? AND paid_at IS NULL');$s->execute([$id]);foreach($s as $o){$days=(int)floor((strtotime($date)-strtotime(substr((string)$o['due_at'],0,10)))/86400);$days=max(0,$days);$pen=$days>=2?round((float)$o['amount']*.0005*($days-1),2):0;$this->pdo->prepare('UPDATE company_obligations SET penalty_amount=?,status=? WHERE id=?')->execute([$pen,$days>0?'late':'pending',$o['id']]);}}
 private function refreshAllObligations():void{foreach($this->pdo->query('SELECT id FROM companies') as $c)$this->refreshObligations((int)$c['id']);}
 public function payObligation(int $companyId,int $id):void{$this->pdo->beginTransaction();try{$o=$this->one('SELECT * FROM company_obligations WHERE id=? AND company_id=? AND paid_at IS NULL FOR UPDATE',[$id,$companyId]);if(!$o)throw new \RuntimeException('Mokėjimas nerastas.');$a=$this->one('SELECT * FROM company_bank_accounts WHERE company_id=? AND is_primary=1 AND is_active=1 LIMIT 1',[$companyId]);if(!$a)throw new \RuntimeException('Nėra pagrindinės banko sąskaitos.');$sum=(float)$o['amount']+(float)$o['penalty_amount'];if((float)$a['balance']<$sum)throw new \RuntimeException('Nepakanka lėšų pagrindinėje sąskaitoje.');$bal=(float)$a['balance']-$sum;$this->pdo->prepare('UPDATE company_bank_accounts SET balance=? WHERE id=?')->execute([$bal,$a['id']]);$this->pdo->prepare("UPDATE company_obligations SET paid_at=NOW(),status='paid' WHERE id=?")->execute([$id]);$this->pdo->prepare('INSERT INTO bank_account_transactions(account_id,transaction_type,amount,balance_after,reference_type,reference_id,description) VALUES(?,?,?,?,?,?,?)')->execute([$a['id'],'state_payment',-$sum,$bal,'obligation',$id,$o['description']]);$this->pdo->commit();}catch(\Throwable$e){if($this->pdo->inTransaction())$this->pdo->rollBack();throw$e;}}
 private function marketRevenue(array $c):float{$m=$this->one('SELECT * FROM market_demand WHERE city=? AND industry=?',[(string)($c['city']?:'Vilnius'),(string)($c['industry']?:'retail')]);$d=(float)($m['demand_index']??100);$p=(float)($m['purchasing_power']??$this->param('purchasing_power'));$employees=(int)($this->one('SELECT employees FROM company_employment WHERE company_id=?',[$c['id']])['employees']??0);$competition=(int)($this->one("SELECT COUNT(*) v FROM companies WHERE city=? AND industry=? AND status='active' AND id<>?",[$c['city'],$c['industry'],$c['id']])['v']??0);$capacity=max(1000,$employees*2200);$share=1/(1+$competition*.12);return round($capacity*($d/100)*($p/100)*$share,2);}
 private function utilityCost(int $id):float{$sum=0;$s=$this->pdo->prepare('SELECT * FROM company_utility_contracts WHERE company_id=? AND is_active=1');$s->execute([$id]);foreach($s as $x)$sum+=(float)$x['monthly_usage']*$this->param((string)$x['utility_type']);return round($sum,2);}
 private function param(string $k):float{$r=$this->one('SELECT value FROM economic_parameters WHERE parameter_key=? LIMIT 1',[$k]);return(float)($r['value']??0);}
 private function one(string $sql,array $p=[]):array|false{$s=$this->pdo->prepare($sql);$s->execute($p);return$s->fetch();}
}
