<?php
declare(strict_types=1);
namespace MyGame\Infrastructure\Economy;
use PDO;
final class GameEconomyEngine{
 public function __construct(private PDO $pdo){}
 public function clock():array{return $this->pdo->query('SELECT * FROM game_clock WHERE id=1')->fetch()?:[];}
 public function advance(int $days=1):string{$days=max(1,min(31,$days));$old=$this->clock();$from=new \DateTimeImmutable((string)$old['game_date']);$to=$from->modify('+'.$days.' day');$this->pdo->prepare('UPDATE game_clock SET game_date=? WHERE id=1')->execute([$to->format('Y-m-d')]);$this->processMonths($from,$to);return $to->format('Y-m-d');}
 private function processMonths(\DateTimeImmutable $from,\DateTimeImmutable $to):void{if($from->format('Y-m')===$to->format('Y-m'))return;foreach($this->pdo->query('SELECT id FROM companies') as $c)$this->processCompanyMonth((int)$c['id'],$from->format('Y-m'));}
 private function processCompanyMonth(int $companyId,string $period):void{$exists=$this->one('SELECT id FROM company_monthly_cycles WHERE company_id=? AND period=?',[$companyId,$period]);if($exists)return;$company=$this->one('SELECT * FROM companies WHERE id=?',[$companyId]);if(!$company)return;$emp=$this->one('SELECT * FROM company_employment WHERE company_id=?',[$companyId]);$rent=(float)($this->one("SELECT COALESCE(SUM(monthly_rent),0) v FROM company_properties WHERE company_id=? AND status='active'",[$companyId])['v']??0);$utilities=$this->utilityCost($companyId);$payroll=$emp?(int)$emp['employees']*(float)$emp['average_salary']:0;$payrollTax=round($payroll*$this->param('payroll_burden')/100,2);$revenue=$this->marketRevenue($company);$vat=round(max(0,$revenue)*$this->param('vat')/(100+$this->param('vat')),2);$profit=max(0,$revenue-$rent-$utilities-$payroll-$payrollTax);$profitTax=round($profit*$this->param('profit_tax')/100,2);$s=$this->pdo->prepare('INSERT INTO company_monthly_cycles(company_id,period,revenue,rent_cost,utility_cost,payroll_cost,payroll_tax,vat_due,profit_tax_due) VALUES(?,?,?,?,?,?,?,?,?)');$s->execute([$companyId,$period,$revenue,$rent,$utilities,$payroll,$payrollTax,$vat,$profitTax]);$due=(new \DateTimeImmutable($period.'-01'))->modify('+1 month +14 days')->format('Y-m-d');foreach([['VMI','vat','PVM',$vat],['VMI','profit_tax','Pelno mokestis',$profitTax],['SODRA','payroll_tax','Darbo mokesčiai',$payrollTax],['NT','rent','Patalpų nuoma',$rent],['UTILITIES','utilities','Komunalinės paslaugos',$utilities]] as $o){if($o[3]<=0)continue;$q=$this->pdo->prepare("INSERT INTO company_obligations(company_id,institution,obligation_type,description,amount,due_at,status) VALUES(?,?,?,?,?,?,'pending')");$q->execute([$companyId,$o[0],$o[1],$o[2].' · '.$period,$o[3],$due]);}$this->pdo->prepare('UPDATE companies SET monthly_revenue=?,monthly_profit=?,age_months=age_months+1 WHERE id=?')->execute([$revenue,$profit-$profitTax,$companyId]);}
 public function refreshObligations(int $companyId):void{$date=(string)($this->clock()['game_date']??date('Y-m-d'));$s=$this->pdo->prepare("SELECT * FROM company_obligations WHERE company_id=? AND paid_at IS NULL");$s->execute([$companyId]);foreach($s as $o){$days=max(0,(int)(new \DateTimeImmutable((string)$o['due_at']))->diff(new \DateTimeImmutable($date))->format('%r%a'));$pen=$days>=2?round((float)$o['amount']*.0005*($days-1),2):0;$status=$days>0?'late':'pending';$this->pdo->prepare('UPDATE company_obligations SET penalty_amount=?,status=? WHERE id=?')->execute([$pen,$status,$o['id']]);}}
 public function payObligation(int $companyId,int $id):void{$this->pdo->beginTransaction();try{$o=$this->one('SELECT * FROM company_obligations WHERE id=? AND company_id=? AND paid_at IS NULL FOR UPDATE',[$id,$companyId]);if(!$o)throw new \RuntimeException('Mokėjimas nerastas.');$a=$this->one('SELECT * FROM company_bank_accounts WHERE company_id=? AND is_primary=1 AND is_active=1 LIMIT 1',[$companyId]);if(!$a)throw new \RuntimeException('Nėra pagrindinės banko sąskaitos.');$sum=(float)$o['amount']+(float)$o['penalty_amount'];if((float)$a['balance']<$sum)throw new \RuntimeException('Nepakanka lėšų pagrindinėje sąskaitoje.');$bal=(float)$a['balance']-$sum;$this->pdo->prepare('UPDATE company_bank_accounts SET balance=? WHERE id=?')->execute([$bal,$a['id']]);$this->pdo->prepare("UPDATE company_obligations SET paid_at=NOW(),status='paid' WHERE id=?")->execute([$id]);$q=$this->pdo->prepare('INSERT INTO bank_account_transactions(account_id,transaction_type,amount,balance_after,reference_type,reference_id,description) VALUES(?,?,?,?,?,?,?)');$q->execute([$a['id'],'state_payment',-$sum,$bal,'obligation',$id,$o['description']]);$this->pdo->commit();}catch(\Throwable $e){if($this->pdo->inTransaction())$this->pdo->rollBack();throw $e;}}
 private function marketRevenue(array $c):float{$city=(string)($c['city']?:'Vilnius');$industry=(string)($c['industry']?:'retail');$m=$this->one('SELECT * FROM market_demand WHERE city=? AND industry=?',[$city,$industry]);$d=$m?(float)$m['demand_index']:100;$p=$m?(float)$m['purchasing_power']:$this->param('purchasing_power');$employees=(int)($this->one('SELECT employees FROM company_employment WHERE company_id=?',[$c['id']])['employees']??0);$base=max(1000,$employees*2200);return round($base*($d/100)*($p/100),2);}
 private function utilityCost(int $id):float{$sum=0;$s=$this->pdo->prepare('SELECT * FROM company_utility_contracts WHERE company_id=? AND is_active=1');$s->execute([$id]);foreach($s as $x)$sum+=(float)$x['monthly_usage']*$this->param((string)$x['utility_type']);return round($sum,2);}
 private function param(string $key):float{$r=$this->one('SELECT value FROM economic_parameters WHERE parameter_key=? LIMIT 1',[$key]);return(float)($r['value']??0);}
 private function one(string $sql,array $p=[]):array|false{$s=$this->pdo->prepare($sql);$s->execute($p);return$s->fetch();}
}
