<?php
declare(strict_types=1);
namespace MyGame\Infrastructure\Economy;
use PDO;
final class MoneyFlowService{
 public function __construct(private PDO $pdo){}
 public function companyBalance(int $companyId):float{$s=$this->pdo->prepare('SELECT COALESCE(SUM(balance),0) FROM company_bank_accounts WHERE company_id=? AND is_active=1');$s->execute([$companyId]);return(float)$s->fetchColumn();}
 public function sectorBalance(string $code):float{$s=$this->pdo->prepare('SELECT balance FROM economy_sectors WHERE code=?');$s->execute([$code]);return(float)$s->fetchColumn();}
 public function sectorToCompany(string $sector,int $companyId,float $amount,string $type,string $description):float{if($amount<=0)return 0;$sec=$this->sector($sector,true);$a=$this->account($companyId,true);$amount=min($amount,(float)$sec['balance']);if($amount<=0)return 0;$sb=(float)$sec['balance']-$amount;$cb=(float)$a['balance']+$amount;$this->pdo->prepare('UPDATE economy_sectors SET balance=? WHERE id=?')->execute([$sb,$sec['id']]);$this->pdo->prepare('UPDATE company_bank_accounts SET balance=? WHERE id=?')->execute([$cb,$a['id']]);$this->sectorTx((int)$sec['id'],$companyId,-$amount,$sb,$type,$description);$this->companyTx((int)$a['id'],$amount,$cb,$type,$description);return$amount;}
 public function companyToSector(int $companyId,string $sector,float $amount,string $type,string $description):void{if($amount<=0)return;$a=$this->account($companyId,true);if((float)$a['balance']<$amount)throw new \RuntimeException('Nepakanka lėšų: '.$description);$sec=$this->sector($sector,true);$cb=(float)$a['balance']-$amount;$sb=(float)$sec['balance']+$amount;$this->pdo->prepare('UPDATE company_bank_accounts SET balance=? WHERE id=?')->execute([$cb,$a['id']]);$this->pdo->prepare('UPDATE economy_sectors SET balance=? WHERE id=?')->execute([$sb,$sec['id']]);$this->companyTx((int)$a['id'],-$amount,$cb,$type,$description);$this->sectorTx((int)$sec['id'],$companyId,$amount,$sb,$type,$description);}
 public function companyToCompany(int $from,int $to,float $amount,string $type,string $description):void{if($amount<=0)return;if($from===$to)throw new \RuntimeException('Negalima pervesti pinigų tai pačiai įmonei.');$fa=$this->account($from,true);$ta=$this->account($to,true);if((float)$fa['balance']<$amount)throw new \RuntimeException('Nepakanka lėšų.');$fb=(float)$fa['balance']-$amount;$tb=(float)$ta['balance']+$amount;$this->pdo->prepare('UPDATE company_bank_accounts SET balance=? WHERE id=?')->execute([$fb,$fa['id']]);$this->pdo->prepare('UPDATE company_bank_accounts SET balance=? WHERE id=?')->execute([$tb,$ta['id']]);$this->companyTx((int)$fa['id'],-$amount,$fb,$type,$description);$this->companyTx((int)$ta['id'],$amount,$tb,$type,$description);}
 private function account(int $id,bool $lock=false):array{$sql='SELECT * FROM company_bank_accounts WHERE company_id=? AND is_primary=1 AND is_active=1 LIMIT 1'.($lock?' FOR UPDATE':'');$s=$this->pdo->prepare($sql);$s->execute([$id]);$a=$s->fetch();if(!$a)throw new \RuntimeException('Įmonė neturi pagrindinės banko sąskaitos.');return$a;}
 private function sector(string $code,bool $lock=false):array{$sql='SELECT * FROM economy_sectors WHERE code=?'.($lock?' FOR UPDATE':'');$s=$this->pdo->prepare($sql);$s->execute([$code]);$x=$s->fetch();if(!$x)throw new \RuntimeException('Ekonomikos sektorius nerastas.');return$x;}
 private function companyTx(int $account,float $amount,float $balance,string $type,string $description):void{$this->pdo->prepare('INSERT INTO bank_account_transactions(account_id,transaction_type,amount,balance_after,reference_type,description,game_date) VALUES(?,?,?,?,?,?,(SELECT game_date FROM game_clock WHERE id=1))')->execute([$account,$type,$amount,$balance,'money_flow',$description]);}
 private function sectorTx(int $sector,?int $company,float $amount,float $balance,string $type,string $description):void{$date=(string)$this->pdo->query('SELECT game_date FROM game_clock WHERE id=1')->fetchColumn();$this->pdo->prepare('INSERT INTO economy_sector_transactions(sector_id,company_id,transaction_type,amount,balance_after,description,game_date) VALUES(?,?,?,?,?,?,?)')->execute([$sector,$company,$type,$amount,$balance,$description,$date]);}
}
