<?php
declare(strict_types=1);
namespace MyGame\Infrastructure\Banking;
use PDO;
final class DatabaseLoanRepository {
 public function __construct(private PDO $pdo){}
 public function company(int $id): ?array {$s=$this->pdo->prepare('SELECT * FROM companies WHERE id=?');$s->execute([$id]);return $s->fetch()?:null;}
 public function ensureDemoCompany(): array {$c=$this->company(1);if($c)return $c;$country=(int)$this->pdo->query("SELECT id FROM countries WHERE code='LT' LIMIT 1")->fetchColumn();$s=$this->pdo->prepare('INSERT INTO companies(country_id,name,cash,assets,liabilities,monthly_revenue,monthly_profit,age_months) VALUES(?,?,?,?,?,?,?,?)');$s->execute([$country,'Mano įmonė',25000,40000,5000,18000,3200,18]);return $this->company((int)$this->pdo->lastInsertId());}
 public function accounts(int $companyId): array {$s=$this->pdo->prepare('SELECT a.*,b.name bank_name,b.code bank_code FROM company_bank_accounts a JOIN banks b ON b.id=a.bank_id WHERE a.company_id=? AND a.is_active=1 ORDER BY a.is_primary DESC,a.id');$s->execute([$companyId]);return $s->fetchAll();}
 public function ensurePrimaryAccount(array $company): array {$accounts=$this->accounts((int)$company['id']);if($accounts)return $accounts[0];$bank=(int)$this->pdo->query('SELECT id FROM banks WHERE is_active=1 ORDER BY id LIMIT 1')->fetchColumn();if(!$bank)throw new \RuntimeException('Nėra aktyvaus banko sąskaitai sukurti.');$bankCode=(string)$this->pdo->query('SELECT code FROM banks WHERE id='.(int)$bank)->fetchColumn();$bankCode=strtoupper(substr(preg_replace('/[^A-Za-z0-9]/','',$bankCode),0,2));$number='LT'.str_pad((string)(10+((int)$company['id']%89)),2,'0',STR_PAD_LEFT).str_pad($bankCode,2,'0').str_pad((string)$bank,4,'0',STR_PAD_LEFT).str_pad((string)$company['id'],8,'0',STR_PAD_LEFT);$s=$this->pdo->prepare('INSERT INTO company_bank_accounts(company_id,bank_id,account_number,currency,balance,is_primary) VALUES(?,?,?,?,?,1)');$s->execute([(int)$company['id'],$bank,$number,'EUR',(float)$company['cash']]);return $this->accounts((int)$company['id'])[0];}
 public function transactions(int $accountId,int $limit=10): array {$s=$this->pdo->prepare('SELECT * FROM bank_account_transactions WHERE account_id=? ORDER BY created_at DESC,id DESC LIMIT '.max(1,min(100,$limit)));$s->execute([$accountId]);return $s->fetchAll();}
 public function banks(): array {$sql="SELECT b.*,p.id product_id,p.name product_name,p.min_amount,p.max_amount,p.max_term_months,p.margin product_margin,p.min_equity_percent FROM banks b JOIN bank_loan_products p ON p.bank_id=b.id AND p.is_active=1 WHERE b.is_active=1 ORDER BY b.id";return $this->pdo->query($sql)->fetchAll();}
 public function policy(): array {$s=$this->pdo->query("SELECT parameter_key,value FROM economic_parameters WHERE section='banking'");$r=[];foreach($s as $p)$r[$p['parameter_key']]=(float)$p['value'];return $r;}
 public function createApplication(int $companyId,array $bank,float $amount,int $months,array $result): int {$status=$result['approved']?'approved':'rejected';$s=$this->pdo->prepare('INSERT INTO loan_applications(company_id,bank_id,loan_product_id,requested_amount,requested_term_months,equity_percent,risk_score,risk_margin,offered_interest_rate,status,decision_reason,decided_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,NOW())');$s->execute([$companyId,$bank['id'],$bank['product_id'],$amount,$months,$result['equity_percent'],$result['risk_score'],$result['risk_margin'],$result['interest_rate'],$status,$result['reason']]);return (int)$this->pdo->lastInsertId();}
}
