<?php
declare(strict_types=1);
namespace MyGame\Infrastructure\Banking;
use PDO;
final class DatabaseLoanRepository {
 public function __construct(private PDO $pdo){}
 public function company(int $id): ?array {$s=$this->pdo->prepare('SELECT * FROM companies WHERE id=?');$s->execute([$id]);return $s->fetch()?:null;}
 public function ensureDemoCompany(): array {$c=$this->company(1);if($c)return $c;$country=(int)$this->pdo->query("SELECT id FROM countries WHERE code='LT' LIMIT 1")->fetchColumn();$s=$this->pdo->prepare('INSERT INTO companies(country_id,name,cash,assets,liabilities,monthly_revenue,monthly_profit,age_months) VALUES(?,?,?,?,?,?,?,?)');$s->execute([$country,'Mano įmonė',25000,40000,5000,18000,3200,18]);return $this->company((int)$this->pdo->lastInsertId());}
 public function accounts(int $companyId): array {$s=$this->pdo->prepare('SELECT a.*,b.name bank_name,b.code bank_code FROM company_bank_accounts a JOIN banks b ON b.id=a.bank_id WHERE a.company_id=? AND a.is_active=1 ORDER BY a.is_primary DESC,a.id');$s->execute([$companyId]);return $s->fetchAll();}
 public function accountAtBank(int $companyId,int $bankId): ?array {$s=$this->pdo->prepare('SELECT a.*,b.name bank_name,b.code bank_code FROM company_bank_accounts a JOIN banks b ON b.id=a.bank_id WHERE a.company_id=? AND a.bank_id=? AND a.is_active=1 LIMIT 1');$s->execute([$companyId,$bankId]);return $s->fetch()?:null;}
 public function openAccount(int $companyId,int $bankId): array {if($a=$this->accountAtBank($companyId,$bankId))return $a;$s=$this->pdo->prepare('SELECT id,code FROM banks WHERE id=? AND is_active=1');$s->execute([$bankId]);$b=$s->fetch();if(!$b)throw new \RuntimeException('Bankas nerastas arba neaktyvus.');$has=(bool)$this->accounts($companyId);$code=strtoupper(substr(preg_replace('/[^A-Za-z0-9]/','',(string)$b['code']),0,2));$number='LT'.str_pad((string)(10+($companyId%89)),2,'0',STR_PAD_LEFT).str_pad($code,2,'0').str_pad((string)$bankId,4,'0',STR_PAD_LEFT).str_pad((string)$companyId,8,'0',STR_PAD_LEFT);$q=$this->pdo->prepare('INSERT INTO company_bank_accounts(company_id,bank_id,account_number,currency,balance,is_primary) VALUES(?,?,?,?,0,?)');$q->execute([$companyId,$bankId,$number,'EUR',$has?0:1]);return $this->accountAtBank($companyId,$bankId);}
 public function setPrimaryAccount(int $companyId,int $accountId): void {$this->pdo->beginTransaction();try{$s=$this->pdo->prepare('SELECT id FROM company_bank_accounts WHERE id=? AND company_id=? AND is_active=1');$s->execute([$accountId,$companyId]);if(!$s->fetchColumn())throw new \RuntimeException('Sąskaita nerasta.');$this->pdo->prepare('UPDATE company_bank_accounts SET is_primary=0 WHERE company_id=?')->execute([$companyId]);$this->pdo->prepare('UPDATE company_bank_accounts SET is_primary=1 WHERE id=? AND company_id=?')->execute([$accountId,$companyId]);$this->pdo->commit();}catch(\Throwable $e){if($this->pdo->inTransaction())$this->pdo->rollBack();throw $e;}}
 public function transactions(int $accountId,int $limit=10): array {$s=$this->pdo->prepare('SELECT * FROM bank_account_transactions WHERE account_id=? ORDER BY created_at DESC,id DESC LIMIT '.max(1,min(100,$limit)));$s->execute([$accountId]);return $s->fetchAll();}
 public function banks(): array {$sql="SELECT b.*,p.id product_id,p.name product_name,p.min_amount,p.max_amount,p.max_term_months,p.margin product_margin,p.min_equity_percent FROM banks b JOIN bank_loan_products p ON p.bank_id=b.id AND p.is_active=1 WHERE b.is_active=1 ORDER BY b.id";return $this->pdo->query($sql)->fetchAll();}
 public function policy(): array {$s=$this->pdo->query("SELECT parameter_key,value FROM economic_parameters WHERE section='banking'");$r=[];foreach($s as $p)$r[$p['parameter_key']]=(float)$p['value'];return $r;}
 public function application(int $id,int $companyId): ?array {$s=$this->pdo->prepare("SELECT a.*,b.name bank_name,p.name product_name FROM loan_applications a JOIN banks b ON b.id=a.bank_id LEFT JOIN bank_loan_products p ON p.id=a.loan_product_id WHERE a.id=? AND a.company_id=?");$s->execute([$id,$companyId]);return $s->fetch()?:null;}
 public function activeLoans(int $companyId): array {$s=$this->pdo->prepare("SELECT l.*,b.name bank_name,a.requested_amount FROM company_loans l JOIN banks b ON b.id=l.bank_id JOIN loan_applications a ON a.id=l.application_id WHERE l.company_id=? AND l.status='active' ORDER BY l.started_at DESC");$s->execute([$companyId]);return $s->fetchAll();}
 public function acceptApplication(int $applicationId,int $companyId,float $monthlyPayment): array {$this->pdo->beginTransaction();try{$app=$this->application($applicationId,$companyId);if(!$app||$app['status']!=='approved')throw new \RuntimeException('Šio paskolos pasiūlymo priimti negalima.');$account=$this->accountAtBank($companyId,(int)$app['bank_id']);if(!$account)throw new \RuntimeException('Paskolos banke nėra aktyvios įmonės sąskaitos.');$amount=(float)$app['requested_amount'];$newBalance=(float)$account['balance']+$amount;$this->pdo->prepare('UPDATE company_bank_accounts SET balance=? WHERE id=?')->execute([$newBalance,$account['id']]);$this->pdo->prepare('UPDATE companies SET liabilities=liabilities+? WHERE id=?')->execute([$amount,$companyId]);$this->pdo->prepare("UPDATE loan_applications SET status='accepted' WHERE id=?")->execute([$applicationId]);$s=$this->pdo->prepare("INSERT INTO company_loans(application_id,company_id,bank_id,principal,outstanding_principal,annual_interest_rate,term_months,monthly_payment,started_at,next_payment_at,status) VALUES(?,?,?,?,?,?,?,?,NOW(),DATE_ADD(NOW(),INTERVAL 1 MONTH),'active')");$s->execute([$applicationId,$companyId,$app['bank_id'],$amount,$amount,$app['offered_interest_rate'],$app['requested_term_months'],$monthlyPayment]);$loanId=(int)$this->pdo->lastInsertId();$t=$this->pdo->prepare("INSERT INTO bank_account_transactions(account_id,transaction_type,amount,balance_after,reference_type,reference_id,description) VALUES(?,?,?,?,?,?,?)");$t->execute([$account['id'],'loan_disbursement',$amount,$newBalance,'loan',$loanId,'Verslo paskolos išmokėjimas · '.$app['bank_name']]);$this->pdo->commit();return ['loan_id'=>$loanId,'account_id'=>(int)$account['id'],'balance'=>$newBalance];}catch(\Throwable $e){if($this->pdo->inTransaction())$this->pdo->rollBack();throw $e;}}
 public function createApplication(int $companyId,array $bank,float $amount,int $months,array $result): int {$status=$result['approved']?'approved':'rejected';$s=$this->pdo->prepare('INSERT INTO loan_applications(company_id,bank_id,loan_product_id,requested_amount,requested_term_months,equity_percent,risk_score,risk_margin,offered_interest_rate,status,decision_reason,decided_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,NOW())');$s->execute([$companyId,$bank['id'],$bank['product_id'],$amount,$months,$result['equity_percent'],$result['risk_score'],$result['risk_margin'],$result['interest_rate'],$status,$result['reason']]);return (int)$this->pdo->lastInsertId();}
}
