<!doctype html><html lang="lt"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>MyGame Admin</title><link rel="stylesheet" href="../assets/admin.css"></head><body>
<aside class="sidebar"><div class="brand">MYGAME <span>ADMIN</span></div><small>VALSTYBĖS</small><div class="country">🇱🇹 <b>Lietuva</b><span>EUR</span></div><nav><a href="treasury.php">💶 Valstybės finansai</a><?php foreach($admin['sections'] as $key=>$label): ?><a class="<?= $section===$key?'active':'' ?>" href="?section=<?= urlencode($key) ?>"><?= htmlspecialchars($label) ?></a><?php endforeach; ?></nav><div class="bottom">⚙ Sistemos nustatymai</div></aside>
<main><header><div><small>VALSTYBĖ / LIETUVA</small><h1><?= htmlspecialchars($admin['sections'][$section]) ?></h1></div><div class="admin-badge">ADMINISTRATORIUS</div></header>
<div class="notice"><b>Valstybės ekonomikos valdymas</b><span>Šie parametrai tiesiogiai veiks žaidėjų įmonių sąnaudas, paklausą ir finansavimą.</span></div>
<?php if($error): ?><div class="notice error dismissible"><button type="button" class="notice-close" onclick="this.parentElement.remove()">×</button><b>Klaida</b><span><?= htmlspecialchars($error) ?></span></div><?php elseif($saved): ?><div class="notice dismissible"><button type="button" class="notice-close" onclick="this.parentElement.remove()">×</button><b>Pakeitimai išsaugoti</b><span>Naujos reikšmės ir jų įsigaliojimo data įrašytos į istoriją.</span></div><?php endif; ?>
<section class="content"><form method="post" id="economy-form" onkeydown="if(event.key==='Enter' && event.target.matches('input[name^=values]')){event.preventDefault();this.requestSubmit();}"><input type="hidden" name="csrf" value="<?= htmlspecialchars($csrf) ?>"><div class="section-head"><div><h2><?= htmlspecialchars($admin['sections'][$section]) ?></h2><p>Pakeiskite reikšmę ir spauskite Enter – pakeitimas bus išsaugotas.</p></div><div class="save-tools"><label>Įsigalioja nuo <input type="date" name="effective_from" value="<?= htmlspecialchars($effectiveFrom) ?>"></label></div></div>
<?php $moduleHelp=[
'economy'=>['Ekonomikos valdymas','Pagrindiniai šalies ekonomikos rodikliai, kurie vėliau veiks paklausą, kainas ir verslo aktyvumą.'],
'energy'=>['Energetikos valdymas','Bazinės energijos kainos, tiekimo pajėgumas ir stabilumas.'],
'water'=>['Vandens ir nuotekų valdymas','Vandens, nuotekų kainos bei infrastruktūros pajėgumas ir stabilumas.'],
'banking'=>['Bankų sistemos valdymas','Palūkanos, paskolų sąlygos ir kreditavimo prieinamumas įmonėms.'],
'taxes'=>['Mokesčių valdymas','Pagrindiniai verslui ir jo savininkams taikomi mokesčiai.'],
'transport'=>['Transporto valdymas','Kuro kainos, logistikos kaštai ir šalies transporto pajėgumas.'],
'labour'=>['Darbo rinkos valdymas','Atlyginimai, nedarbas, darbuotojų pasiūla ir darbo našumas.'],
'real_estate'=>['NT rinkos valdymas','Komercinių, sandėliavimo ir gamybinių patalpų kainų bei pasiūlos bazė.'],
'trade'=>['Importo ir eksporto valdymas','Tarptautinės prekybos kaštai, muitai ir sienų efektyvumas.'],
'population'=>['Gyventojų valdymas','Gyventojų skaičius, perkamoji galia ir darbo rinkai svarbi demografija.']
]; $help=$moduleHelp[$section]??null; if($help): ?><div class="module-info"><b><?= htmlspecialchars($help[0]) ?></b><span><?= htmlspecialchars($help[1]) ?></span></div><?php endif; ?><div class="parameter-list"><?php if(!$parameters&&!$error): ?><div class="empty">Šio skyriaus parametrų nėra.</div><?php endif; ?><?php foreach($parameters as $p): ?><div class="parameter"><div><b><?= htmlspecialchars($p->label) ?></b><small><?= htmlspecialchars($p->key) ?></small></div><div class="value"><?php if(in_array($p->key,['automatic_pricing','automatic_water_pricing'],true)): ?><select name="values[<?= htmlspecialchars($p->key) ?>]" onchange="this.form.submit()"><option value="0" <?= $p->value<0.5?'selected':'' ?>>Išjungta</option><option value="1" <?= $p->value>=0.5?'selected':'' ?>>Įjungta</option></select><?php else: ?><input name="values[<?= htmlspecialchars($p->key) ?>]" type="text" inputmode="decimal" autocomplete="off" value="<?= htmlspecialchars((string)$p->value) ?>"><span><?= htmlspecialchars($p->unit) ?></span><?php endif; ?></div></div><?php endforeach; ?></div></form></section>
<?php if($section==='banking' && $banks): ?><section class="content banks"><div class="section-head"><div><h2>Komerciniai bankai</h2><p>Bankų paskolų palūkanos apskaičiuojamos iš valstybės normų ir konkretaus banko maržos.</p></div></div><div class="bank-grid"><?php foreach($banks as $b): ?><article class="bank-card"><div class="bank-title"><div><b><?= htmlspecialchars($b['name']) ?></b><small><?= htmlspecialchars($b['code']) ?></small></div><span class="<?= $b['is_active']?'active-bank':'inactive-bank' ?>"><?= $b['is_active']?'AKTYVUS':'IŠJUNGTAS' ?></span></div><div class="bank-rate"><small>VERSLO PASKOLA NUO</small><strong><?= htmlspecialchars(number_format((float)$b['effective_loan_rate'],2,',',' ')) ?>%</strong></div><div class="bank-stats"><span>Kapitalas <b><?= htmlspecialchars(number_format((float)$b['capital']/1000000,1,',',' ')) ?> mln. €</b></span><span>Likvidumas <b><?= htmlspecialchars((string)(float)$b['liquidity_index']) ?> ind.</b></span><span>Rizikos apetitas <b><?= htmlspecialchars((string)(float)$b['risk_appetite']) ?> ind.</b></span><span>Banko marža <b><?= htmlspecialchars(number_format((float)$b['loan_margin'],2,',',' ')) ?>%</b></span><?php if($b['product_name']): ?><span>Paskolos suma <b><?= htmlspecialchars(number_format((float)$b['min_amount'],0,',',' ')) ?>–<?= htmlspecialchars(number_format((float)$b['max_amount'],0,',',' ')) ?> €</b></span><span>Terminas iki <b><?= htmlspecialchars((string)$b['max_term_months']) ?> mėn.</b></span><?php endif; ?></div></article><?php endforeach; ?></div><div class="rate-note">Skaičiavimas: bazinė palūkanų norma + banko marža + paskolos produkto marža. Konkrečios įmonės rizikos priedas bus pridedamas vertinant paskolos paraišką.</div></section><?php endif; ?>
<section class="content history"><div class="section-head"><div><h2>Pakeitimų istorija</h2><p>Paskutiniai šio skyriaus kainų ir parametrų pakeitimai.</p></div></div>
<?php if(!$history): ?><div class="empty">Pakeitimų istorijos dar nėra.</div><?php else: ?><div class="history-table"><div class="history-row head"><span>Parametras</span><span>Buvo</span><span>Nauja</span><span>Įsigalioja</span><span>Pakeista</span></div><?php foreach($history as $h): ?><div class="history-row"><b><?= htmlspecialchars($h['label']) ?></b><span><?= htmlspecialchars((string)(float)$h['old_value'].' '.$h['unit']) ?></span><span><?= htmlspecialchars((string)(float)$h['new_value'].' '.$h['unit']) ?></span><span><?= htmlspecialchars(date('Y-m-d',strtotime($h['effective_from']))) ?></span><span><?= htmlspecialchars(date('Y-m-d H:i',strtotime($h['changed_at']))) ?></span></div><?php endforeach; ?></div><?php endif; ?></section>
</main></body></html>
