<!doctype html><html lang="lt"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>MyGame Admin</title><link rel="stylesheet" href="../assets/admin.css"></head><body>
<aside class="sidebar"><div class="brand">MYGAME <span>ADMIN</span></div><small>VALSTYBĖS</small><div class="country">🇱🇹 <b>Lietuva</b><span>EUR</span></div><nav><?php foreach($admin['sections'] as $key=>$label): ?><a class="<?= $section===$key?'active':'' ?>" href="?section=<?= urlencode($key) ?>"><?= htmlspecialchars($label) ?></a><?php endforeach; ?></nav><div class="bottom">⚙ Sistemos nustatymai</div></aside>
<main><header><div><small>VALSTYBĖ / LIETUVA</small><h1><?= htmlspecialchars($admin['sections'][$section]) ?></h1></div><div class="admin-badge">ADMINISTRATORIUS</div></header>
<div class="notice"><b>Valstybės ekonomikos valdymas</b><span>Šie parametrai tiesiogiai veiks žaidėjų įmonių sąnaudas, paklausą ir finansavimą.</span></div>
<?php if($error): ?><div class="notice error"><b>Klaida</b><span><?= htmlspecialchars($error) ?></span></div><?php elseif($saved): ?><div class="notice"><b>Pakeitimai išsaugoti</b><span>Naujos reikšmės ir jų įsigaliojimo data įrašytos į istoriją.</span></div><?php endif; ?>
<section class="content"><form method="post"><input type="hidden" name="csrf" value="<?= htmlspecialchars($csrf) ?>"><div class="section-head"><div><h2><?= htmlspecialchars($admin['sections'][$section]) ?></h2><p>Valdykite šios srities ekonominius parametrus.</p></div><div class="save-tools"><label>Įsigalioja nuo <input type="date" name="effective_from" value="<?= htmlspecialchars($effectiveFrom) ?>"></label><button type="submit" <?= $error?'disabled':'' ?>>Išsaugoti pakeitimus</button></div></div>
<div class="parameter-list"><?php if(!$parameters&&!$error): ?><div class="empty">Šio skyriaus parametrų nėra.</div><?php endif; ?><?php foreach($parameters as $p): ?><div class="parameter"><div><b><?= htmlspecialchars($p->label) ?></b><small><?= htmlspecialchars($p->key) ?></small></div><div class="value"><input name="values[<?= htmlspecialchars($p->key) ?>]" type="text" inputmode="decimal" autocomplete="off" value="<?= htmlspecialchars((string)$p->value) ?>"><span><?= htmlspecialchars($p->unit) ?></span></div></div><?php endforeach; ?></div></form></section>
<section class="content history"><div class="section-head"><div><h2>Pakeitimų istorija</h2><p>Paskutiniai šio skyriaus kainų ir parametrų pakeitimai.</p></div></div>
<?php if(!$history): ?><div class="empty">Pakeitimų istorijos dar nėra.</div><?php else: ?><div class="history-table"><div class="history-row head"><span>Parametras</span><span>Buvo</span><span>Nauja</span><span>Įsigalioja</span><span>Pakeista</span></div><?php foreach($history as $h): ?><div class="history-row"><b><?= htmlspecialchars($h['label']) ?></b><span><?= htmlspecialchars((string)(float)$h['old_value'].' '.$h['unit']) ?></span><span><?= htmlspecialchars((string)(float)$h['new_value'].' '.$h['unit']) ?></span><span><?= htmlspecialchars(date('Y-m-d',strtotime($h['effective_from']))) ?></span><span><?= htmlspecialchars(date('Y-m-d H:i',strtotime($h['changed_at']))) ?></span></div><?php endforeach; ?></div><?php endif; ?></section>
</main></body></html>
