<!doctype html><html lang="lt"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>MyGame Admin – Sistemos diagnostika</title><link rel="stylesheet" href="../assets/admin.css"></head><body>
<aside class="sidebar"><div class="brand">MYGAME <span>ADMIN</span></div><small>DIAGNOSTIKA</small><nav><a href="treasury.php">💶 Valstybės finansai</a><a href="index.php">⚙ Ekonomikos valdymas</a><a href="ai-diagnostics.php">🤖 AI įmonės</a><a class="active" href="system-diagnostics.php">🩺 Sistemos diagnostika</a></nav><div class="bottom">Tikrinimas nieko nekeičia</div></aside>
<main><header><div><small>ADMIN / DIAGNOSTIKA</small><h1>Sistemos diagnostika</h1><p>Žaidimo data: <?=htmlspecialchars($gameDate)?></p></div><div class="admin-badge">TIK SKAITYMAS</div></header>
<?php if($error):?><div class="notice error"><b>Klaida</b><span><?=htmlspecialchars($error)?></span></div><?php endif;?>
<section class="content treasury-wide"><div class="section-head"><div><h2>Audito suvestinė</h2><p>Greita visos žaidimo būsenos santrauka.</p></div></div><div class="treasury-stats"><div class="stat"><small>ĮMONĖS</small><strong><?=number_format((int)($stats['companies']??0),0,',',' ')?></strong></div><div class="stat"><small>CIKLAI</small><strong><?=number_format((int)($stats['cycles']??0),0,',',' ')?></strong></div><div class="stat"><small>KLAIDOS</small><strong><?=(int)($stats['errors']??0)?></strong></div><div class="stat"><small>ĮSPĖJIMAI</small><strong><?=(int)($stats['warnings']??0)?></strong></div></div></section>
<section class="content treasury-wide"><div class="section-head"><div><h2>Rastos problemos</h2><p>Konkreti įmonė ir vieta, kurią reikia tikrinti. Diagnostika duomenų nekeičia.</p></div></div><?php if(empty($issues)):?><div class="notice"><b>✓ Kritinių neatitikimų nerasta</b><span>Visi šiuo metu tikrinami ryšiai atrodo tvarkingi.</span></div><?php else:?><div style="overflow:auto"><table style="width:100%;border-collapse:collapse"><thead><tr><th>Sritis</th><th>Įmonė</th><th>Laikotarpis</th><th>Problema</th><th>Lygis</th></tr></thead><tbody><?php foreach($issues as $x):?><tr><td><?=htmlspecialchars($x['area'])?></td><td><b><?=htmlspecialchars($x['company'])?></b></td><td><?=htmlspecialchars((string)$x['period'])?></td><td><?=htmlspecialchars($x['detail'])?></td><td><b style="color:<?=$x['level']==='error'?'#ef8f9a':'#e9c46a'?>"><?=$x['level']==='error'?'KLAIDA':'ĮSPĖJIMAS'?></b></td></tr><?php endforeach;?></tbody></table></div><?php endif;?></section>
<section class="content treasury-wide"><div class="section-head"><div><h2>Bendri patikrinimai</h2><p>Duomenų bazė, atsargos ir pardavimų vientisumas.</p></div></div>
<?php foreach($checks as $x):?><div class="parameter"><div><b><?=($x['level']==='ok'?'✓':'✕')?> <?=htmlspecialchars($x['title'])?></b><small><?=htmlspecialchars($x['detail'])?></small></div><strong style="color:<?=$x['level']==='ok'?'#67dbaa':'#ef8f9a'?>"><?=$x['level']==='ok'?'GERAI':'KLAIDA'?></strong></div><?php endforeach;?></section>
<section class="content treasury-wide"><div class="section-head"><div><h2>Pardavimų paleidimo diagnostika</h2><p>Parodo, ar kiekviena aktyvi įmonė šiuo metu turi visas sąlygas pardavimams pradėti.</p></div></div><div style="overflow:auto"><table style="width:100%;border-collapse:collapse"><thead><tr><th>Įmonė</th><th>Miestas / veikla</th><th>Patalpos</th><th>Darbuotojas</th><th>Komunalinės</th><th>Atsargos</th><th>Paklausa</th><th>HOUSEHOLDS</th><th>Rezultatas</th></tr></thead><tbody>
<?php foreach($salesReadiness as $r):?><tr><td><b><?=htmlspecialchars($r['name'])?></b></td><td><?=htmlspecialchars($r['city'].' · '.$r['industry'])?></td><td><?=$r['property']?'✓':'✕'?></td><td><?=$r['employee']?'✓':'✕'?></td><td><?=$r['utilities']?'✓':'✕'?><?php if(!$r['utilities']):?><br><small><?=htmlspecialchars(implode(', ',$r['missing_utilities']))?></small><?php endif;?></td><td><?=$r['stock']?'✓ '.number_format((float)$r['stock_qty'],2,',',' '):'✕ 0'?></td><td><?=$r['demand']?'✓ '.number_format((float)$r['demand_index'],0,',',' ').' / '.number_format((float)$r['purchasing_power'],0,',',' '):'✕'?></td><td><?=number_format((float)$r['households'],2,',',' ')?> €</td><td><b style="color:<?=$r['ready']?'#67dbaa':'#ef8f9a'?>"><?=$r['ready']?'✓ PARUOŠTA':'✕ BLOKUOJAMA'?></b><?php if(!$r['ready']):?><br><small><?=htmlspecialchars(implode('; ',$r['blockers']))?></small><?php endif;?></td></tr><?php endforeach;?></tbody></table></div></section>
<section class="content treasury-wide"><div class="section-head"><div><h2>Pardavimų variklio skaičiavimas</h2><p>READ ONLY: perskaičiuoja dabartinę salesRevenue() formulę nekeisdamas atsargų, banko ar ciklų.</p></div></div>
<?php foreach($salesEngine as $e):?><div class="parameter" style="display:block;margin-bottom:14px"><div style="display:flex;justify-content:space-between;gap:16px;flex-wrap:wrap"><div><b><?=htmlspecialchars($e['name'])?></b><small><?=htmlspecialchars($e['city'].' · '.$e['industry'])?> · paskutinis ciklas <?=htmlspecialchars((string)$e['last_period'])?>: <?=number_format((float)$e['last_revenue'],2,',',' ')?> €</small></div><strong>PLANAS: <?=number_format((float)$e['planned_qty'],2,',',' ')?> vnt. · <?=number_format((float)$e['planned_revenue'],2,',',' ')?> €</strong></div>
<div style="margin-top:10px;overflow:auto"><table style="width:100%;border-collapse:collapse"><thead><tr><th>Paklausa</th><th>Perkamoji galia</th><th>Brand</th><th>Marketingas</th><th>Konkurentai</th><th>HOUSEHOLDS</th><th>Galima apmokėti</th></tr></thead><tbody><tr><td><?=number_format((float)$e['demand'],2,',',' ')?></td><td><?=number_format((float)$e['power'],2,',',' ')?></td><td><?=number_format((float)$e['brand'],2,',',' ')?></td><td><?=number_format((float)$e['budget'],2,',',' ')?> €</td><td><?=(int)$e['competition']?></td><td><?=number_format((float)$e['households'],2,',',' ')?> €</td><td><?=number_format((float)$e['payable_revenue'],2,',',' ')?> €</td></tr></tbody></table></div>
<?php if(empty($e['products'])):?><small style="display:block;margin-top:10px;color:#ef8f9a">Nėra produktų su teigiamu likučiu.</small><?php else:?><div style="margin-top:10px;overflow:auto"><table style="width:100%;border-collapse:collapse"><thead><tr><th>Produktas</th><th>Likutis</th><th>Kaina / bazė</th><th>Demand weight</th><th>Elasticity</th><th>Price effect</th><th>Formulės paklausa</th><th>Planuojama</th><th>Pajamos</th></tr></thead><tbody><?php foreach($e['products'] as $p):?><tr><td><?=htmlspecialchars($p['name'])?></td><td><?=number_format((float)$p['stock'],2,',',' ')?></td><td><?=number_format((float)$p['price'],2,',',' ')?> / <?=number_format((float)$p['base_price'],2,',',' ')?></td><td><?=number_format((float)$p['weight'],3,',',' ')?></td><td><?=number_format((float)$p['elasticity'],3,',',' ')?></td><td><?=number_format((float)$p['price_effect'],3,',',' ')?></td><td><?=number_format((float)$p['demand_units'],0,',',' ')?> vnt.</td><td><?=number_format((float)$p['planned_qty'],2,',',' ')?> vnt.</td><td><?=number_format((float)$p['planned_revenue'],2,',',' ')?> €</td></tr><?php endforeach;?></tbody></table></div><?php endif;?></div><?php endforeach;?></section>
<section class="content treasury-wide"><div class="section-head"><div><h2>Pardavimų grandinė</h2><p>sales_ledger → mėnesio ciklas → banko įplauka. Paskutiniai 100 ciklų.</p></div></div><div style="overflow:auto"><table style="width:100%;border-collapse:collapse"><thead><tr><th>Įmonė</th><th>Mėnuo</th><th>Sales ledger</th><th>Monthly cycle</th><th>Bankas</th><th>Būsena</th></tr></thead><tbody>
<?php foreach($rows as $r):?><tr><td><b><?=htmlspecialchars($r['name'])?></b></td><td><?=htmlspecialchars($r['period'])?></td><td><?=number_format((float)$r['ledger_revenue'],2,',',' ')?> €</td><td><?=number_format((float)$r['cycle_revenue'],2,',',' ')?> €</td><td><?=number_format((float)$r['bank_revenue'],2,',',' ')?> €</td><td><b style="color:<?=$r['level']==='ok'?'#67dbaa':'#ef8f9a'?>"><?=$r['level']==='ok'?'✓ SUTAMPA':'✕ NESUTAMPA'?></b></td></tr><?php endforeach;?></tbody></table></div></section>
</main></body></html>